### PR TITLE
Remove reference to Schema Validator

### PR DESCRIPTION
**Pull request by ghost**
I'm assuming you meant Kulture instead of Schema Validator here.

### CODE REVIEW

**Comment by ghost** [comment]
Oops, should I have submitted this to https://github.com/shirhatti/vNext instead? Your repo is the one listed on https://sublime.wbond.net/packages/Kulture (is @shirhatti the project maintainer for Kulture?)

**Comment by shirhatti** [comment]
@voltagex Could you tell me the difference between using `@powershell -NoProfile -Execut...` and `powershell -NoProfile -Execut...`?
I'm not sure about what difference it makes?

I've copied those instructions from the [ASP.NET Home](https://github.com/aspnet/Home)

**Comment by shirhatti** [comment]
Also, https://sublime.wbond.net/packages/Kulture links to [this repo](https://github.com/ligershark/Kulture/)

Is there anything I can do to clarify the confusion?

**Comment by ghost** [comment]
The @ didn't work for me when I tried it.

**Comment by shirhatti** [comment]
Did you paste the command into `cmd.exe` or `powershell.exe`?
According to the instructions, you are to paste the command into `cmd.exe`

**Comment by ghost** [comment]
You are correct. Sorry about that!

**Comment by shirhatti** [comment]
Can you update your PR? I will merge it

**Comment by ghost** [comment]
Done.

**Comment by shirhatti** [comment]
:thumbsup:

**Pull request merged**
